_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.9.22
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 13
                - 55
                - 61
            "4": 3.9.22
            "5": 0.20.0
            "12": 0.20.0
            "13": linux-x86_64
